### ISSUE TITLE
Link spam in homepage

### ISSUE THREAD

**Issue by fabio1310** [Italian-Translation-Alliance/cairn-ita#18]
Come da titolo, nella home del sito tradotto, sul nome "Stefano Grassi", è presente un link ad un profilo twitter che posta spam, nudi e truffe.
Dubito fortemente che sia il suo profilo ufficiale.

**Comment by frollo** [comment]
Grazie per la segnalazione, ho iniziato a rimuovere il link.

Lascio aperto l'issue per ricordarci di inserire il link corretto una volta che lo ritroviamo.

**Comment by frollo** [comment]
Abbiamo aggiunto il nuovo sito di Stefano.
